### PR TITLE
Create validate_operator.py

### PR DESCRIPTION
**Pull request by shreyas3775**
The validate_operator function takes in no input and prompts the user for an operator. It ensures input is a valid operator and return the operator

### CODE REVIEW

**Comment by shreyas3775** [comment]
Does this function seem good to you guys?

**Review by basema-k — APPROVED** [review]
Looks good, Shreya!

**Comment by noorsyed16** [comment]
Yes, it looks good!

**Review by noorsyed16 — APPROVED** [review]
I reviewed the code and it looks good!

**Review by noorsyed16 — CHANGES_REQUESTED** [review]
The code looks good but I think you need to add a function documentation to this file as well :)

**Comment by shreyas3775** [comment]
That sounds good! I'll make the changes and request again

**Review by noorsyed16 — APPROVED** [review]
That looks good now, thanks for making the changes!

**Pull request merged**
